### ISSUE TITLE
can we make rpm packages in addition to debs?

### ISSUE THREAD

**Issue by Dieterbe** [raintank/graphite-api#15]

**Comment by woodsaj** [comment]
we dont build graphite-api packages.  we only build graphite-metrictank pacakges (which include graphite-api in the package).

So this is a duplicated of https://github.com/raintank/graphite-metrictank/issues/28

**Comment by Dieterbe** [comment]
huh then what is https://github.com/raintank/graphite-api/blob/master/pkg/package.sh ?

**Comment by woodsaj** [comment]
old code that should be removed.

**Comment by Dieterbe** [comment]
also https://packagecloud.io/app/raintank/raintank/search?filter=all&q=graphite-api then needs to be removed i guess?

**Comment by woodsaj** [comment]
deleted.
